{% set version = '0.93-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-robustbase
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/robustbase_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/robustbase/robustbase_{{ version }}.tar.gz
  sha256: 27b282ef2c91274f6d88ba0cea468d1078c5d37639cdb141c538a61dc7b96298

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: grid, MASS, lattice, boot, cluster, Matrix, robust, fit.models, MPV, xtable, ggplot2, GGally, RColorBrewer, reshape2, sfsmisc, catdata, doParallel, foreach, skewt
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-deoptimr

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-deoptimr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('robustbase')"           # [not win]
    - "\"%R%\" -e \"library('robustbase')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://robustbase.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: '"Essential" Robust Statistics. Tools allowing to analyze data with robust methods.  This
    includes regression methodology including model selections and multivariate statistics
    where we strive to cover the book "Robust Statistics, Theory and Methods" by ''Maronna,
    Martin and Yohai''; Wiley 2006.'

  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: robustbase
# Version: 0.93-2
# VersionNote: Released 0.93-1.1 on 2018-07-18 on CRAN
# Date: 2018-07-26
# Title: Basic Robust Statistics
# Authors@R: c(person("Martin","Maechler", role=c("aut","cre"), email="maechler@stat.math.ethz.ch") , person("Peter", "Rousseeuw", role="ctb", comment = "Qn and Sn") , person("Christophe", "Croux", role="ctb", comment = "Qn and Sn") , person("Valentin", "Todorov", role = "aut", email = "valentin.todorov@chello.at", comment = "most robust Cov") , person("Andreas", "Ruckstuhl", role = "aut", email = "andreas.ruckstuhl@zhaw.ch", comment = "nlrob, anova, glmrob") , person("Matias", "Salibian-Barrera", role = "aut", email = "matias@stat.ubc.ca", comment = "lmrob orig.") , person("Tobias", "Verbeke", role = c("ctb","fnd"), email = "tobias.verbeke@openanalytics.eu", comment = "mc, adjbox") , person("Manuel", "Koller", role = "aut", email = "koller.manuel@gmail.com", comment = "mc, lmrob, psi-func.") , person(c("Eduardo", "L. T."), "Conceicao", role = "aut", email = "mail@eduardoconceicao.org", comment = "MM-, tau-, CM-, and MTL- nlrob") , person("Maria", "Anna di Palma", role = "ctb", comment = "initial version of Comedian") )
# URL: http://robustbase.r-forge.r-project.org/
# Description: "Essential" Robust Statistics. Tools allowing to analyze data with robust methods.  This includes regression methodology including model selections and multivariate statistics where we strive to cover the book "Robust Statistics, Theory and Methods" by 'Maronna, Martin and Yohai'; Wiley 2006.
# Depends: R (>= 3.1.0)
# Imports: stats, graphics, utils, methods, DEoptimR
# Suggests: grid, MASS, lattice, boot, cluster, Matrix, robust, fit.models, MPV, xtable, ggplot2, GGally, RColorBrewer, reshape2, sfsmisc, catdata, doParallel, foreach, skewt
# SuggestsNote: mostly only because of vignette graphics and simulation
# ByteCompile: yes
# LazyData: yes
# NeedsCompilation: yes
# License: GPL (>= 2)
# Packaged: 2018-07-27 07:28:53 UTC; maechler
# Author: Martin Maechler [aut, cre], Peter Rousseeuw [ctb] (Qn and Sn), Christophe Croux [ctb] (Qn and Sn), Valentin Todorov [aut] (most robust Cov), Andreas Ruckstuhl [aut] (nlrob, anova, glmrob), Matias Salibian-Barrera [aut] (lmrob orig.), Tobias Verbeke [ctb, fnd] (mc, adjbox), Manuel Koller [aut] (mc, lmrob, psi-func.), Eduardo L. T. Conceicao [aut] (MM-, tau-, CM-, and MTL- nlrob), Maria Anna di Palma [ctb] (initial version of Comedian)
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Repository: CRAN
# Date/Publication: 2018-07-27 17:00:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
