travis:
  secure:
    BINSTAR_TOKEN: KgO6Qcj8CPZO0NRPVJfYkueFhKF/f2TUZDYd/pxEJOEYD+QkBJ1t3XwRmmx5HW01DJfD3ZlZJbPtIwPVtOYNukMo3qjm/lSTTjSCgilygl3Nu/d5/rnIlTYhB8igvxQOaVxhY8CZLSoLUYvCxfnTtcHPDOkrxs3qDxgJ4AWjm50knzrF/KmoHgL4PxKVCPPIq990UDLEN8AaDrkinjZDIr83YCizBhMTL5XSqYqSx6aHw/+IOlo2L5RSGymLUDGbh6nA+HQyoYY1zSt0+Fo62qbeo83whb2LFKB5rUTJtVYEcz/9MYBboz4fhJH2YnyRqNo7riAPCW1ciXfG45Zq9NsrQCRAN2NxZaqGHQFoWIP95s+7qINrg+DisJyqCbHY+57VtA2cMueWxmYb48rfzXsS8/q6/2aA+X2xVBWJIbcPuMJHoepYSFlcJv5Ar8AQVNc/leS/bXukMoutu0zfSMKlvzoavfldKtBs6se81a89qOljNChVZZHY1C9M1A5wA1b8eloYFZw4Ksk28dKc9TeGfEy1d2UgVzcBT7HGL72Oapul0eWcy/OfHyeLHopoLKGqhC3Bi/jgDI3+rP3g7hrjA1Uhh6SQdt8gPs0oY3/fBoVP/O78NHEtz5IMwFEy5mADUbZ6p6bh3ULdNOqzLwRIf6cyx/NSzbra/KsObA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
