travis:
  secure:
    BINSTAR_TOKEN: cgJZtIO4clIBBoEzYSejSEEh8N9466QGh46CuqR61D0S2+ECful2IiFej/kQQuJVJv2WPCM3xnN/zf+7E4KCmoQBqxjp2pNTfAYPRs/e8lBMn/CeeQBAAHTZ71UeXFUwAm74qAiH3ro66yT1yiGYL0rRo/NG1aQ+5yre3KxXGFe5BrJ6d6Qq2eNYQxTsJI7UXWcEMTtJXXZPNTO7pElGNc1WXIMF9eOivBMn9/OYgB+l441Jg4ccN9WA9iacaNUc9lUCoydPtZYe9W73PnsPFyka/sTYTD1LhLMZUOrOlATUx0DNTYzzqeZkwm7zzVfCwcWF5mR9rGkmga6OQRSV+/BterdHZSxCwn1PFtK1IK9HPMH7Zk0UU5WICf6zL9tE2vi0WOk3R0ivNImBKj6RH/I5ANQo/jawjHngDY4yn05pS5yzOA9544N64QF67dWepcycErnH93xFLrWzkDNHk4X5asaDxanM1mRIqX0iEyWQnUrBnALua9YLDcjondMwkzOTwVmWPOp0Ib3kfeG4UQxtfAaUMm9pqXsN2gU/0gTHviME5RsBHEod51O5zE8RbNepFwUcx5K0PzpkU9lZsFXGHoEk9H/LHdCZYNZ6KZYnwYFJ/Ziy5Lz5wLCUqk0feSevOvlhDbonm0Q2P8xkY+iPGb5BOSLwZZ2tp77gUoo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
